# Como fritar un huevo de forma sencilla:
print("¿Desea fritar un huevo?")
respuesta = input("Escriba 'si' o 'no': ")

# Si la respuesta es 'si', entonces empezamos:
if respuesta == "si":
    # si la respuesta es "sí" iniciar el programa
    print("calentar la sarten por un minuto...")
    print("echar aceite o mantequilla...")
    print("romper y echar el huevo en la sarten...")
    print("revolver hasta que tenga una buena textura...")
    print("Servir el huevo en un plato.")
    
elif respuesta == "no":
    # Si la respuesta es 'no', finalizar el programa
    print("No se fritará el huevo...")
    exit()
